version: 2

jobs:

  node14_pg10:
    docker:
      - image: circleci/node:14
      - image: circleci/postgres:10
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          LC_COLLATE: C
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install -y postgresql-client
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn lint
      - run:
          command: yarn test
          environment:
            TEST_DATABASE_URL: postgres://circleci@localhost:5432/circle_test

  node16_pg12:
    docker:
      - image: circleci/node:16
      - image: circleci/postgres:12
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          LC_COLLATE: C
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install -y postgresql-client
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn lint
      - run:
          command: yarn test
          environment:
            TEST_DATABASE_URL: postgres://circleci@localhost:5432/circle_test

  node17_pg14:
    docker:
      - image: circleci/node:17
      - image: circleci/postgres:14
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          LC_COLLATE: C
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install -y postgresql-client
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn lint
      - run:
          command: yarn test
          environment:
            TEST_DATABASE_URL: postgres://circleci@localhost:5432/circle_test

workflows:
  version: 2
  test:
    jobs:
      - node14_pg10
      - node16_pg12
      - node17_pg14
